-- Create the STUDENT table
CREATE TABLE STUDENT (
    STUDENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    MIDDLE_NAMES VARCHAR(100),
    LAST_NAME VARCHAR(100) NOT NULL,
    REGISTER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PHONE_NUMBER VARCHAR(20)
);

-- Create the COURSE table
CREATE TABLE COURSE (
    COURSE_ID INT AUTO_INCREMENT PRIMARY KEY,
    COURSE_NAME VARCHAR(100) NOT NULL,
    COURSE_BOOK VARCHAR(100)
);

-- Create the TERM table
CREATE TABLE TERM (
    TERM_ID INT AUTO_INCREMENT PRIMARY KEY,
    TERM_START TIMESTAMP NOT NULL,
    TERM_END TIMESTAMP NOT NULL
);

-- Create the TEACHER table
CREATE TABLE TEACHER (
    TEACHER_ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    MIDDLE_NAMES VARCHAR(100),
    LAST_NAME VARCHAR(100) NOT NULL,
    PHONE_NUMBER VARCHAR(20)
);

-- Create the CLASS table
CREATE TABLE CLASS (
    CLASS_ID INT AUTO_INCREMENT PRIMARY KEY,
    COURSE_ID INT NOT NULL,
    TERM_ID INT NOT NULL,
    TEACHER_ID INT NOT NULL,
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID),
    FOREIGN KEY (TERM_ID) REFERENCES TERM(TERM_ID),
    FOREIGN KEY (TEACHER_ID) REFERENCES TEACHER(TEACHER_ID)
);

-- Create the REGISTRATION table
CREATE TABLE REGISTRATION (
    REGISTRATION_ID INT AUTO_INCREMENT PRIMARY KEY,
    STUDENT_ID INT NOT NULL,
    CLASS_ID INT NOT NULL,
    PRICE INT,
    PAID INT,
    PARTICIPATION_MARK INT,
    ATTENDANCE_MARK INT,
    MID_EXAM_MARK INT,
    HOMEWORKS_MARK INT,
    ACTIVITES_MARK INT,
    FINAL_EXAM_MARK INT,
    TEACHER_COMMENT VARCHAR(255),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
    FOREIGN KEY (CLASS_ID) REFERENCES CLASS(CLASS_ID)
);
